core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

doc_platform:
    resource: "@docPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform    
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#pour activer les annotation des routes dans le dossier Controller    
app:
    resource: "@docPlatformBundle/Controller"
    type:     annotation
app1:
    resource: "@docPlatformBundle/Controller/General"
    type:     annotation
app2:
    resource: "@docPlatformBundle/Controller/DefaultController/Gestion/Agent"
    type:     annotation
app3: 
    resource: "@docPlatformBundle/Controller/DefaultController/Referentiel/General"
    type:     annotation
app4: 
    resource: "@docPlatformBundle/Controller/DefaultController/Traitement/Identite"
    type:     annotation